version: '3.8'

services:
  mongodb:
    image: mongo:latest # Use the official MongoDB image from Docker Hub
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017' # Map the container's MongoDB port to the host port
    volumes:
      - mongodb_data:/data/db # Persist data in a named volume
    environment:
      # Set up root username and password
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  mongodb_data:
    driver: local
